export const SET_SECTION_VIEWPORT_PENDING = 'SET_SECTION_VIEWPORT_PENDING';
export const SET_SECTION_VIEWPORT_FULFILLED = 'SET_SECTION_VIEWPORT_FULFILLED';
export const SET_SECTION_VIEWPORT_REJECTED = 'SET_SECTION_VIEWPORT_REJECTED';
