export const SET_SECTION_VIEWPORT = 'app/SET_SECTION_VIEWPORT';
export const GET_FAKE_API = 'app/GET_FAKE_API';
export const GET_FAKE_API_PENDING = 'app/GET_FAKE_API_PENDING';
export const GET_FAKE_API_FULFILLED = 'app/GET_FAKE_API_FULFILLED';
export const GET_FAKE_API_REJECTED = 'app/GET_FAKE_API_REJECTED';